EmchBerger/cube-common-bundle

src/Project/ProjectVersionGit.php

Returns the tag which the current commit bases on

added getClosestTagString method

---

src/DataHandling/Logs/DataDogAudit.php
src/DataHandling/Logs/LogsInterface.php

[Logs] handling DataDogAuditBundle

---

src/Resources/views/Emails/subscriptionMessageContent.html.twig
src/Subscriptions/Conditions/AbstractCondition.php
src/Subscriptions/MailSubscription.php
src/Subscriptions/Message/AbstractParticipantsProvider.php
src/Subscriptions/Message/ContentGenerator.php
src/Subscriptions/Message/ParticipantsGenerator.php
src/Subscriptions/Reports/AbstractReport.php
src/Subscriptions/Reports/ExcelReportTrait.php

- business logic for subscriptions
- frontend is application specific and needs to be implemented there

#18 Adding subscription mechanism backend

---

src/DataHandling/Logs/DataDogAudit.php

- change of name and value for constants with key for elements, that were not changed

#22 Change of name and value for constants with key for elements, that were not changed

---

src/DataHandling/Logs/DataDogAudit.php

- remove column from logs if only unchanged elements exists

remove column from logs if only unchanged elements exists

---

composer.json

Note: The dependencies were resorted by composer. Must have done something wrong in f508b76.

[composer] install css-selector in dev for running ExcelConverterTest

---

src/Resources/public/cubecommon.js

work around twbs/bootstrap#16732

[ColumnSelector] update click state when closing overflow

---

src/DataHandling/CollectionHandler.php
src/Form/ColumnsExtractor.php

[Collection] support for processing raw html elements added #66

---

src/Resources/config/services.yml

[Collection] making service for ColumnsExtractor #66

---

src/Form/ColumnsExtractor.php

[CustomFieldsColumns] extraction of custom fields implemented #79

---

src/Filter/FilterQueryCondition.php

IntegerRange based on Daterange.

[FilterQueryCondition] Implement andWhereIntegerRange

---

src/Resources/public/cubecommon.js

* set variable colId in both cases
* variable colId is local
* use colClass when checking columns (colId was there by mistake)
* compare the jquery element with .is() method (=== does something different)

[ColumnSelection] fix js code detecting same column group

---

composer.json
src/CubeToolsCubeCommonBundle.php
src/DataHandling/StringHelper.php
src/Resources/config/services.yml
src/Security/VersatileFormLoginLdapFactory.php
src/Security/VersatileLdapBindAuthenticationProvider.php
src/Security/VersatileUserProvider.php

fügt eine Erweiterung des FosUserProvider und des LdapBindAuthenticationProvider hinzu, die benötigt werden für https://github.com/EmchBerger/projectassistant/pull/2025

1869 versatile user provider

---

src/Resources/config/services.yml
src/Security/VersatileFormLoginLdapFactory.php
src/Security/VersatileLdapBindAuthenticationProvider.php

added anonymous LDAP bind() call to VersatileLdapBindAuthenticationProvider, make it more robust in case the LDAP is misconfigured

added anonymous LDAP bind() call to VersatileLdapBindAuthenticationProvider

---

src/Resources/config/services.yml
src/Security/VersatileFormLoginLdapFactory.php
src/Security/VersatileLdapBindAuthenticationProvider.php

Config aufgeräumt und näher am Symfony Standard.

VersatileLdapBindAuthentication

---

src/Entity/Common/NotificationsRepositoryTrait.php
src/Filter/FilterEntityQueryBuilder.php
src/Subscriptions/Conditions/Notifications.php
tests/Filter/FilterEntityQueryBuilderTest.php
tests/Subscriptions/Conditions/NotificationsTest.php

- getterProvider functionality to handle nested joins while emulating database query
#117

117 notifications methods

---

src/DataHandling/Logs/DataDogAudit.php
src/DataHandling/Logs/LogsFunctionsTrait.php
tests/DataHandling/Logs/LogsFunctionsTraitTest.php

includes #120 (needs to be merged first)
#122

122 logs filtering

---

src/FileFormat/ExcelConverter.php
src/Resources/config/services.yml
tests/FileFormat/ExcelConverterTest.php

#43 
In order to have projects, which don't need to have LiuggoBundle and PHPExcel.

[PhpExcel] dependency on PhpExcel optional #43

---

Makefile

some commands for dev can be simply run with `make xxx`
Please try:
* make check-changes
* make
* vendor/bin/check-files-cube.sh some/file/to.test

[general development] add makefile as provided by CubeCommonDevelop

---

composer.json
phpstan.neon.dist

To use new feature in config (scanFiles or bootstrapFiles instead of autoload_files).

[testing] update phpstan and its config
